import {
  USER1,
  USER2,
  USER3,
  USER4,
  USER5,
  USER6,
  USER7,
  USER8,
  USER9,
  USER10,
  POST1,
  POST2,
  POST3,
  POST4,
  POST5,
  POST6,
  POST7,
  POST8,
  POST9,
  POST10,
  POST11,
  POST12,
  POST13,
  POST14,
  POST15,
  POST16,
  POST17,
  POST18,
  POST19,
  POST20,
  POST21,
  POST22,
  POST23,
  POST24,
  POST25,
  POST26,
  POST27,
  POST28,
  POST29,
  POST30,
  POST31,
  POST32,
  POST33,
  POST34,
  POST35,
  POST36,
  POST37,
  POST38,
  POST39,
  POST40,
  POST41,
  POST42,
  POST43,
  POST44,
  POST45,
  POST46,
  POST47,
  POST48,
  POST49,
  POST50,
} from "../assets/images";
import { PostType } from "../types/postTypes";

export const posts: PostType[] = [
  {
    created_at: "2022-11-01",
    userId: 1,
    userAvi: USER1,
    username: "Bret",
    id: 1,
    caption:
      "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    media: POST1,
    likes: 19,
  },
  {
    created_at: "2022-11-02",
    userId: 1,
    userAvi: USER1,
    username: "Bret",
    id: 2,
    caption:
      "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
    media: POST2,
    likes: 437,
  },
  {
    created_at: "2022-11-03",
    userId: 1,
    userAvi: USER1,
    username: "Bret",
    id: 3,
    caption:
      "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
    media: POST3,
    likes: 369,
  },
  {
    created_at: "2022-11-04",
    userId: 1,
    userAvi: USER1,
    username: "Bret",
    id: 4,
    caption:
      "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
    media: POST4,
    likes: 28,
  },
  {
    created_at: "2022-11-05",
    userId: 1,
    userAvi: USER1,
    username: "Bret",
    id: 5,
    caption:
      "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
    media: POST5,
    likes: 403,
  },
  {
    created_at: "2022-11-23",
    userId: 2,
    userAvi: USER2,
    username: "Antonette",
    id: 11,
    caption:
      "delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi",
    media: POST6,
    likes: 157,
  },
  {
    created_at: "2022-11-25",
    userId: 2,
    userAvi: USER2,
    username: "Antonette",
    id: 12,
    caption:
      "itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio",
    media: POST7,
    likes: 383,
  },
  {
    created_at: "2022-11-03",
    userId: 2,
    userAvi: USER2,
    username: "Antonette",
    id: 13,
    caption:
      "aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam",
    media: POST8,
    likes: 93,
  },
  {
    created_at: "2022-11-09",
    userId: 2,
    userAvi: USER2,
    username: "Antonette",
    id: 14,
    caption:
      "fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum",
    media: POST9,
    likes: 183,
  },
  {
    created_at: "2022-11-04",
    userId: 2,
    userAvi: USER2,
    username: "Antonette",
    id: 15,
    caption:
      "reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae",
    media: POST10,
    likes: 419,
  },
  {
    created_at: "2022-11-01",
    userId: 3,
    userAvi: USER3,
    username: "Samantha",
    id: 21,
    caption:
      "repellat aliquid praesentium dolorem quo\nsed totam minus non itaque\nnihil labore molestiae sunt dolor eveniet hic recusandae veniam\ntempora et tenetur expedita sunt",
    media: POST11,
    likes: 117,
  },
  {
    created_at: "2022-11-07",
    userId: 3,
    userAvi: USER3,
    username: "Samantha",
    id: 22,
    caption:
      "eos qui et ipsum ipsam suscipit aut\nsed omnis non odio\nexpedita earum mollitia molestiae aut atque rem suscipit\nnam impedit esse",
    media: POST12,
    likes: 208,
  },
  {
    created_at: "2022-11-17",
    userId: 3,
    userAvi: USER3,
    username: "Samantha",
    id: 23,
    caption:
      "veritatis unde neque eligendi\nquae quod architecto quo neque vitae\nest illo sit tempora doloremque fugit quod\net et vel beatae sequi ullam sed tenetur perspiciatis",
    media: POST13,
    likes: 88,
  },
  {
    created_at: "2022-11-22",
    userId: 3,
    userAvi: USER3,
    username: "Samantha",
    id: 24,
    caption:
      "enim et ex nulla\nomnis voluptas quia qui\nvoluptatem consequatur numquam aliquam sunt\ntotam recusandae id dignissimos aut sed asperiores deserunt",
    media: POST14,
    likes: 25,
  },
  {
    created_at: "2022-11-24",
    userId: 3,
    userAvi: USER3,
    username: "Samantha",
    id: 25,
    caption:
      "ullam consequatur ut\nomnis quis sit vel consequuntur\nipsa eligendi ipsum molestiae et omnis error nostrum\nmolestiae illo tempore quia et distinctio",
    media: POST15,
    likes: 336,
  },
  {
    created_at: "2022-11-11",
    userId: 4,
    userAvi: USER4,
    username: "Karianne",
    id: 31,
    caption:
      "debitis eius sed quibusdam non quis consectetur vitae\nimpedit ut qui consequatur sed aut in\nquidem sit nostrum et maiores adipisci atque\nquaerat voluptatem adipisci repudiandae",
    media: POST16,
    likes: 223,
  },
  {
    created_at: "2022-11-13",
    userId: 4,
    userAvi: USER4,
    username: "Karianne",
    id: 32,
    caption:
      "deserunt eos nobis asperiores et hic\nest debitis repellat molestiae optio\nnihil ratione ut eos beatae quibusdam distinctio maiores\nearum voluptates et aut adipisci ea maiores voluptas maxime",
    media: POST17,
    likes: 431,
  },
  {
    created_at: "2022-11-10",
    userId: 4,
    userAvi: USER4,
    username: "Karianne",
    id: 33,
    caption:
      "rerum ut et numquam laborum odit est sit\nid qui sint in\nquasi tenetur tempore aperiam et quaerat qui in\nrerum officiis sequi cumque quod",
    media: POST18,
    likes: 143,
  },
  {
    created_at: "2022-11-08",
    userId: 4,
    userAvi: USER4,
    username: "Karianne",
    id: 34,
    caption:
      "ea velit perferendis earum ut voluptatem voluptate itaque iusto\ntotam pariatur in\nnemo voluptatem voluptatem autem magni tempora minima in\nest distinctio qui assumenda accusamus dignissimos officia nesciunt nobis",
    media: POST19,
    likes: 224,
  },
  {
    created_at: "2022-11-03",
    userId: 4,
    userAvi: USER4,
    username: "Karianne",
    id: 35,
    caption:
      "nisi error delectus possimus ut eligendi vitae\nplaceat eos harum cupiditate facilis reprehenderit voluptatem beatae\nmodi ducimus quo illum voluptas eligendi\net nobis quia fugit",
    media: POST20,
    likes: 155,
  },
  {
    created_at: "2022-11-18",
    userId: 5,
    userAvi: USER5,
    username: "Kamren",
    id: 41,
    caption:
      "molestias id nostrum\nexcepturi molestiae dolore omnis repellendus quaerat saepe\nconsectetur iste quaerat tenetur asperiores accusamus ex ut\nnam quidem est ducimus sunt debitis saepe",
    media: POST21,
    likes: 304,
  },
  {
    created_at: "2022-11-16",
    userId: 5,
    userAvi: USER5,
    username: "Kamren",
    id: 42,
    caption:
      "odio fugit voluptatum ducimus earum autem est incidunt voluptatem\nodit reiciendis aliquam sunt sequi nulla dolorem\nnon facere repellendus voluptates quia\nratione harum vitae ut",
    media: POST22,
    likes: 250,
  },
  {
    created_at: "2022-11-23",
    userId: 5,
    userAvi: USER5,
    username: "Kamren",
    id: 43,
    caption:
      "similique fugit est\nillum et dolorum harum et voluptate eaque quidem\nexercitationem quos nam commodi possimus cum odio nihil nulla\ndolorum exercitationem magnam ex et a et distinctio debitis",
    media: POST23,
    likes: 278,
  },
  {
    created_at: "2022-11-01",
    userId: 5,
    userAvi: USER5,
    username: "Kamren",
    id: 44,
    caption:
      "temporibus est consectetur dolore\net libero debitis vel velit laboriosam quia\nipsum quibusdam qui itaque fuga rem aut\nea et iure quam sed maxime ut distinctio quae",
    media: POST24,
    likes: 100,
  },
  {
    created_at: "2022-11-08",
    userId: 5,
    userAvi: USER5,
    username: "Kamren",
    id: 45,
    caption:
      "est natus reiciendis nihil possimus aut provident\nex et dolor\nrepellat pariatur est\nnobis rerum repellendus dolorem autem",
    media: POST25,
    likes: 158,
  },
  {
    created_at: "2022-11-21",
    userId: 6,
    userAvi: USER6,
    username: "Leopoldo_Corkery",
    id: 51,
    caption:
      "sunt dolores aut doloribus\ndolore doloribus voluptates tempora et\ndoloremque et quo\ncum asperiores sit consectetur dolorem",
    media: POST26,
    likes: 219,
  },
  {
    created_at: "2022-11-15",
    userId: 6,
    userAvi: USER6,
    username: "Leopoldo_Corkery",
    id: 52,
    caption:
      "iusto est quibusdam fuga quas quaerat molestias\na enim ut sit accusamus enim\ntemporibus iusto accusantium provident architecto\nsoluta esse reprehenderit qui laborum",
    media: POST27,
    likes: 222,
  },
  {
    created_at: "2022-11-13",
    userId: 6,
    userAvi: USER6,
    username: "Leopoldo_Corkery",
    id: 53,
    caption:
      "minima harum praesentium eum rerum illo dolore\nquasi exercitationem rerum nam\nporro quis neque quo\nconsequatur minus dolor quidem veritatis sunt non explicabo similique",
    media: POST28,
    likes: 420,
  },
  {
    created_at: "2022-11-02",
    userId: 6,
    userAvi: USER6,
    username: "Leopoldo_Corkery",
    id: 54,
    caption:
      "totam corporis dignissimos\nvitae dolorem ut occaecati accusamus\nex velit deserunt\net exercitationem vero incidunt corrupti mollitia",
    media: POST29,
    likes: 23,
  },
  {
    created_at: "2022-11-24",
    userId: 6,
    userAvi: USER6,
    username: "Leopoldo_Corkery",
    id: 55,
    caption:
      "debitis excepturi ea perferendis harum libero optio\neos accusamus cum fuga ut sapiente repudiandae\net ut incidunt omnis molestiae\nnihil ut eum odit",
    media: POST30,
    likes: 338,
  },
  {
    created_at: "2022-11-15",
    userId: 7,
    userAvi: USER7,
    username: "Elwyn.Skiles",
    id: 61,
    caption:
      "ab nemo optio odio\ndelectus tenetur corporis similique nobis repellendus rerum omnis facilis\nvero blanditiis debitis in nesciunt doloribus dicta dolores\nmagnam minus velit",
    media: POST31,
    likes: 286,
  },
  {
    created_at: "2022-11-04",
    userId: 7,
    userAvi: USER7,
    username: "Elwyn.Skiles",
    id: 62,
    caption:
      "enim aspernatur illo distinctio quae praesentium\nbeatae alias amet delectus qui voluptate distinctio\nodit sint accusantium autem omnis\nquo molestiae omnis ea eveniet optio",
    media: POST32,
    likes: 35,
  },
  {
    created_at: "2022-11-03",
    userId: 7,
    userAvi: USER7,
    username: "Elwyn.Skiles",
    id: 63,
    caption:
      "enim adipisci aspernatur nemo\nnumquam omnis facere dolorem dolor ex quis temporibus incidunt\nab delectus culpa quo reprehenderit blanditiis asperiores\naccusantium ut quam in voluptatibus voluptas ipsam dicta",
    media: POST33,
    likes: 131,
  },
  {
    created_at: "2022-11-03",
    userId: 7,
    userAvi: USER7,
    username: "Elwyn.Skiles",
    id: 64,
    caption:
      "id velit blanditiis\neum ea voluptatem\nmolestiae sint occaecati est eos perspiciatis\nincidunt a error provident eaque aut aut qui",
    media: POST34,
    likes: 159,
  },
  {
    created_at: "2022-11-03",
    userId: 7,
    userAvi: USER7,
    username: "Elwyn.Skiles",
    id: 65,
    caption:
      "voluptatibus ex esse\nsint explicabo est aliquid cumque adipisci fuga repellat labore\nmolestiae corrupti ex saepe at asperiores et perferendis\nnatus id esse incidunt pariatur",
    media: POST35,
    likes: 261,
  },
  {
    created_at: "2022-11-17",
    userId: 8,
    userAvi: USER8,
    username: "Maxime_Nienow",
    id: 71,
    caption:
      "occaecati a doloribus\niste saepe consectetur placeat eum voluptate dolorem et\nqui quo quia voluptas\nrerum ut id enim velit est perferendis",
    media: POST36,
    likes: 176,
  },
  {
    created_at: "2022-11-11",
    userId: 8,
    userAvi: USER8,
    username: "Maxime_Nienow",
    id: 72,
    caption:
      "quam occaecati qui deleniti consectetur\nconsequatur aut facere quas exercitationem aliquam hic voluptas\nneque id sunt ut aut accusamus\nsunt consectetur expedita inventore velit",
    media: POST37,
    likes: 209,
  },
  {
    created_at: "2022-11-15",
    userId: 8,
    userAvi: USER8,
    username: "Maxime_Nienow",
    id: 73,
    caption:
      "voluptatem cumque tenetur consequatur expedita ipsum nemo quia explicabo\naut eum minima consequatur\ntempore cumque quae est et\net in consequuntur voluptatem voluptates aut",
    media: POST38,
    likes: 195,
  },
  {
    created_at: "2022-11-18",
    userId: 8,
    userAvi: USER8,
    username: "Maxime_Nienow",
    id: 74,
    caption:
      "odit qui et et necessitatibus sint veniam\nmollitia amet doloremque molestiae commodi similique magnam et quam\nblanditiis est itaque\nquo et tenetur ratione occaecati molestiae tempora",
    media: POST39,
    likes: 433,
  },
  {
    created_at: "2022-11-06",
    userId: 8,
    userAvi: USER8,
    username: "Maxime_Nienow",
    id: 75,
    caption:
      "commodi non non omnis et voluptas sit\nautem aut nobis magnam et sapiente voluptatem\net laborum repellat qui delectus facilis temporibus\nrerum amet et nemo voluptate expedita adipisci error dolorem",
    media: POST40,
    likes: 345,
  },
  {
    created_at: "2022-10-05",
    userId: 9,
    userAvi: USER9,
    username: "Delphine",
    id: 81,
    caption:
      "facere qui nesciunt est voluptatum voluptatem nisi\nsequi eligendi necessitatibus ea at rerum itaque\nharum non ratione velit laboriosam quis consequuntur\nex officiis minima doloremque voluptas ut aut",
    media: POST41,
    likes: 484,
  },
  {
    created_at: "2022-11-03",
    userId: 9,
    userAvi: USER9,
    username: "Delphine",
    id: 82,
    caption:
      "ut libero sit aut totam inventore sunt\nporro sint qui sunt molestiae\nconsequatur cupiditate qui iste ducimus adipisci\ndolor enim assumenda soluta laboriosam amet iste delectus hic",
    media: POST42,
    likes: 112,
  },
  {
    created_at: "2022-11-01",
    userId: 9,
    userAvi: USER9,
    username: "Delphine",
    id: 83,
    caption:
      "est molestiae facilis quis tempora numquam nihil qui\nvoluptate sapiente consequatur est qui\nnecessitatibus autem aut ipsa aperiam modi dolore numquam\nreprehenderit eius rem quibusdam",
    media: POST43,
    likes: 160,
  },
  {
    created_at: "2022-11-03",
    userId: 9,
    userAvi: USER9,
    username: "Delphine",
    id: 84,
    caption:
      "sint molestiae magni a et quos\neaque et quasi\nut rerum debitis similique veniam\nrecusandae dignissimos dolor incidunt consequatur odio",
    media: POST44,
    likes: 196,
  },
  {
    created_at: "2022-11-04",
    userId: 9,
    userAvi: USER9,
    username: "Delphine",
    id: 85,
    caption:
      "similique sed nisi voluptas iusto omnis\nmollitia et quo\nassumenda suscipit officia magnam sint sed tempora\nenim provident pariatur praesentium atque animi amet ratione",
    media: POST45,
    likes: 293,
  },
  {
    created_at: "2022-11-24",
    userId: 10,
    userAvi: USER10,
    username: "Moriah.Stanton",
    id: 91,
    caption:
      "libero voluptate eveniet aperiam sed\nsunt placeat suscipit molestias\nsimilique fugit nam natus\nexpedita consequatur consequatur dolores quia eos et placeat",
    media: POST46,
    likes: 216,
  },
  {
    created_at: "2022-11-25",
    userId: 10,
    userAvi: USER10,
    username: "Moriah.Stanton",
    id: 92,
    caption:
      "aut et excepturi dicta laudantium sint rerum nihil\nlaudantium et at\na neque minima officia et similique libero et\ncommodi voluptate qui",
    media: POST47,
    likes: 364,
  },
  {
    created_at: "2022-11-04",
    userId: 10,
    userAvi: USER10,
    username: "Moriah.Stanton",
    id: 93,
    caption:
      "dolorem quibusdam ducimus consequuntur dicta aut quo laboriosam\nvoluptatem quis enim recusandae ut sed sunt\nnostrum est odit totam\nsit error sed sunt eveniet provident qui nulla",
    media: POST48,
    likes: 58,
  },
  {
    created_at: "2022-11-20",
    userId: 10,
    userAvi: USER10,
    username: "Moriah.Stanton",
    id: 94,
    caption:
      "aspernatur expedita soluta quo ab ut similique\nexpedita dolores amet\nsed temporibus distinctio magnam saepe deleniti\nomnis facilis nam ipsum natus sint similique omnis",
    media: POST49,
    likes: 280,
  },
  {
    created_at: "2022-11-19",
    userId: 10,
    userAvi: USER10,
    username: "Moriah.Stanton",
    id: 95,
    caption:
      "earum voluptatem facere provident blanditiis velit laboriosam\npariatur accusamus odio saepe\ncumque dolor qui a dicta ab doloribus consequatur omnis\ncorporis cupiditate eaque assumenda ad nesciunt",
    media: POST50,
    likes: 351,
  },
];
